[Icon Theme]
Name=Windows-7
Comment=Windows 7 Icon Theme for Linux Desktops (GTK 3, GTK 4, XFCE, MATE, Cinnamon, GNOME)
Inherits=elementary,Adwaita,gnome,hicolor

# Directories list
Directories=actions,actions/16,actions/25,actions/32,actions/48,actions/MediaPlayer,animations,apps,apps/16,apps/32,apps/34,apps/64,categories,categories/16,devices,devices/16,devices/48,devices/64,emblems,emotes,filesystems,filesystems/16,places,places/16,mimetypes,mimetypes/16,mimetypes/48,mimetypes/symbolic,notifications,notifications/32,status,status/18,status/20,status/48,status/52,status/64,status/76,status/symbolic,scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/places,scalable/status,symbolic,symbolic/actions,symbolic/categories,symbolic/devices,symbolic/emblems,symbolic/legacy,symbolic/mimetypes,symbolic/status,symbolic/ui

# Actions
[actions]
Size=128
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[actions/16]
Size=16
Context=Actions
MinSize=8
MaxSize=512
Type=Scalable

[actions/25]
Size=24
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[actions/32]
Size=32
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[actions/48]
Size=48
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[actions/MediaPlayer]
Size=38
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

# Animations
[animations]
Size=32
Context=Animations
MinSize=16
MaxSize=512
Type=Scalable

# Applications
[apps]
Size=128
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[apps/16]
Size=16
Context=Applications
MinSize=8
MaxSize=512
Type=Scalable

[apps/32]
Size=32
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[apps/34]
Size=34
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[apps/64]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

# Categories
[categories]
Size=128
Context=Categories
MinSize=16
MaxSize=512
Type=Scalable

[categories/16]
Size=16
Context=Categories
MinSize=8
MaxSize=512
Type=Scalable

# Devices
[devices]
Size=128
Context=Devices
MinSize=16
MaxSize=512
Type=Scalable

[devices/16]
Size=16
Context=Devices
MinSize=8
MaxSize=512
Type=Scalable

[devices/48]
Size=48
Context=Devices
MinSize=16
MaxSize=512
Type=Scalable

[devices/64]
Size=64
Context=Devices
MinSize=16
MaxSize=512
Type=Scalable

# Emblems
[emblems]
Size=128
Context=Emblems
MinSize=16
MaxSize=512
Type=Scalable

# Emotes
[emotes]
Size=21
Context=Emblems
MinSize=16
MaxSize=512
Type=Scalable

# Filesystems / Places
[filesystems]
Size=128
Context=Places
MinSize=16
MaxSize=512
Type=Scalable

[filesystems/16]
Size=16
Context=Places
MinSize=8
MaxSize=512
Type=Scalable

[places]
Size=128
Context=Places
MinSize=16
MaxSize=512
Type=Scalable

[places/16]
Size=16
Context=Places
MinSize=8
MaxSize=512
Type=Scalable

# MimeTypes
[mimetypes]
Size=128
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

[mimetypes/16]
Size=16
Context=MimeTypes
MinSize=8
MaxSize=512
Type=Scalable

[mimetypes/48]
Size=48
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

[mimetypes/symbolic]
Size=16
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

# Notifications
[notifications]
Size=128
Context=Notifications
MinSize=16
MaxSize=512
Type=Scalable

[notifications/32]
Size=45
Context=Notifications
MinSize=16
MaxSize=512
Type=Scalable

# Status
[status]
Size=128
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[status/18]
Size=18
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[status/20]
Size=22
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[status/48]
Size=48
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[status/52]
Size=52
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[status/64]
Size=64
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[status/76]
Size=76
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[status/symbolic]
Size=16
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

# Scalable SVGs
[scalable/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/apps]
Context=Applications
Size=128
MinSize=16
MaxSize=512
Type=Scalable

[scalable/categories]
Context=Categories
Size=128
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=128
MinSize=16
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=128
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=128
MinSize=16
MaxSize=512
Type=Scalable

# Symbolic icons
[symbolic]
Context=Status
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/actions]
Context=Actions
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/categories]
Context=Categories
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/devices]
Context=Devices
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/emblems]
Context=Emblems
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/legacy]
Context=Legacy
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/mimetypes]
Context=MimeTypes
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/status]
Context=Status
Size=16
MinSize=16
MaxSize=512
Type=Scalable

[symbolic/ui]
Context=UI
Size=16
MinSize=16
MaxSize=512
Type=Scalable
